import { MedicationAdministration } from '../models/medication-administration';

export const ADMINISTRATIONS: MedicationAdministration[] = [
    {
        identifier: [{value: '01', type: {text: 'szoveg'}}],
        instantiates: ['protokoll1'],
        partOf: ['sars-cov-2 elleni oltás'],
        status: 'done',
        statusReason: [{text: 'fertőzésmegelőzése'}],
        category: {text: 'oltás'},
        medication: 'Pfizer-Biontech',
        subject: 'Kiss János',
        context: '1. kör oltás',
        supportInformation: ['180cm', '75kg'],
        effective: '2021-04-29',
        performer: [{actor: 'Szabó Béla'}],
        reasonCode: [{text: 'regisztrált'}],
        reasonReference: ['Regisztrált 18 év feletti', 'krónikus beteg'],
        request: 'időpontfoglalás',
        device: ['L512'],
        note: [{text: 'valami szöveg'}],
        dosage: {text: 'semmi különös', site: {text: 'bal kar'}, dose: {value: 5, unit: 'mg'}},
        eventHistory: ['2021-04-27 délután']
    },
    {
        identifier: [{value: '02'}],
        instantiates: ['protokoll1'],
        partOf: ['sars-cov-2 elleni oltás'],
        status: 'done',
        statusReason: [{text: 'fertőzésmegelőzése'}],
        category: {text: 'oltás'},
        medication: 'Pfizer-Biontech',
        subject: 'Kiss János',
        context: '1. kör oltás',
        supportInformation: ['180cm', '75kg'],
        effective: '2021-04-29',
        performer: [{actor: 'Szabó Béla'}],
        reasonCode: [{text: 'regisztrált'}],
        reasonReference: ['Regisztrált 18 év feletti', 'krónikus beteg'],
        request: 'időpontfoglalás',
        device: ['L512'],
        note: [{text: ''}],
        dosage: {text: '', site: {text: ''}, dose: {value: 5, unit: ''}},
        eventHistory: ['2021-04-27 délután']
    },
    {
        identifier: [{value: '03'}],
        instantiates: ['protokoll1'],
        partOf: ['sars-cov-2 elleni oltás'],
        status: 'done',
        statusReason: [{text: 'fertőzésmegelőzése'}],
        category: {text: 'oltás'},
        medication: 'Pfizer-Biontech',
        subject: 'Kiss János',
        context: '1. kör oltás',
        supportInformation: ['180cm', '75kg'],
        effective: '2021-04-29',
        performer: [{actor: 'Szabó Béla'}],
        reasonCode: [{text: 'regisztrált'}],
        reasonReference: ['Regisztrált 18 év feletti', 'krónikus beteg'],
        request: 'időpontfoglalás',
        device: ['L512'],
        note: [{text: ''}],
        dosage: {text: '', site: {text: ''}, dose: {value: 5, unit: ''}},
        eventHistory: ['2021-04-27 délután']
    },
    {
        identifier: [{value: '04'}],
        instantiates: ['protokoll1'],
        partOf: ['sars-cov-2 elleni oltás'],
        status: 'done',
        statusReason: [{text: 'fertőzésmegelőzése'}],
        category: {text: 'oltás'},
        medication: 'Pfizer-Biontech',
        subject: 'Kiss János',
        context: '1. kör oltás',
        supportInformation: ['180cm', '75kg'],
        effective: '2021-04-29',
        performer: [{actor: 'Szabó Béla'}],
        reasonCode: [{text: 'regisztrált'}],
        reasonReference: ['Regisztrált 18 év feletti', 'krónikus beteg'],
        request: 'időpontfoglalás',
        device: ['L512'],
        note: [{text: ''}],
        dosage: {text: '', site: {text: ''}, dose: {value: 5, unit: ''}},
        eventHistory: ['2021-04-27 délután']
    }
];